### ISSUE TITLE
[Bug] [PermissionsViewer] Right clicking a user does not show the view permissions button

### ISSUE THREAD

**Issue by DanBTechnology** [rauenzi/BetterDiscordAddons#351]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
When right clicking a username (either from the member list or from a chat message) the permissions button does not appear

**To Reproduce**
Right click on any user and you will see that the permissions button does not appear

**Expected Behavior**
When right clicking, the permissions button should appear

**Screenshots**
![PermsViewer Bug screenshot](https://user-images.githubusercontent.com/6370453/112867399-e234df80-9088-11eb-9773-ce8ad1686a5e.PNG)

**Discord Version**
Stable 80728 (81b6702)

**Comment by rauenzi** [comment]
This has been fixed in the latest version!

**Comment by BlueStarBRS** [comment]
@rauenzi nope its still not working nothing to see in the dropdown selection

**Comment by BlueStarBRS** [comment]
@rauenzi  
![image](https://user-images.githubusercontent.com/25110093/116816315-bdd59280-ab61-11eb-85f3-950e9b030c3d.png)
