### ISSUE TITLE
[Bug] BetterFormattingRedux

### ISSUE THREAD

**Issue by Nirgranth** [rauenzi/BetterDiscordAddons#584]
Plugin does not work

**Screenshots**
![image](https://user-images.githubusercontent.com/48947296/163573473-22e76848-204c-4257-abf5-b5e817a522bb.png)

**Discord Version**
Stable 123887 (00d8cb1)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
yep same here
```
Stable 124397 (2bf79b5)
BetterDiscord 1.5.3
Host 0.0.266 OS X 10.15.7 (20.6.0)
```

however no logs in console me, anything I click on doesn't work

**Comment by TheEliteGeek** [comment]
Similar issue except I don't see any errors in the console.

**Comment by rauenzi** [comment]
This has been fixed with the latest update!

**Comment by Nirgranth** [comment]
@rauenzi 
Console errors still there, Plugin works
![image](https://user-images.githubusercontent.com/48947296/187430720-5cbee4c7-7f56-459a-8e23-dd4dcf71ff8d.png)
