### ISSUE TITLE
[Bug] Not working

### ISSUE THREAD

**Issue by Daniii5** [rauenzi/BetterDiscordAddons#662]
Plugin could not be compiled"
TypeError: Cannot read property 'Permissions' of undefined
    at plugin (betterdiscord://plugins/PermissionsViewer.plugin.js:225:76)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:951:13)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:952:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Discord Version**:Stable (151638)
[Screenshot](https://imgur.com/a/EbrAuws)

**Comment by Daniii5** [comment]
TypeError: Cannot read property 'Permissions' of undefined
    at plugin (betterdiscord://plugins/PermissionsViewer.plugin.js:225:76)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:951:13)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:952:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.reloadAddon (<anonymous>:4:10047)
    at je.reload (<anonymous>:4:340236)
    at PluginLibrary._reloadPlugins (betterdiscord://plugins/0PluginLibrary.plugin.js:3426:65)
    at PluginLibrary.load (betterdiscord://plugins/0PluginLibrary.plugin.js:3414:18)
    at Object.initializeAddon (<anonymous>:4:42618)
    at Object.loadAddon (<anonymous>:4:9413)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Comment by rauenzi** [comment]
Should be fixed with latest update.

**Comment by Daniii5** [comment]
Hey, still not working for me.
TypeError: Cannot read property 'Permissions' of undefined
    at plugin (betterdiscord://plugins/PermissionsViewer.plugin.js:225:76)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:951:13)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:952:3)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at Object.loadAllAddons (<anonymous>:4:12239)
    at Object.initialize (<anonymous>:4:6705)
    at Object.initialize (<anonymous>:4:36661)
    at Object.startup (<anonymous>:4:381833)
